name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    permissions:
      id-token: write     # OIDC / Trusted Publishing
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip build
      - run: python -m build          # sdist + wheel -> dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
